### ISSUE TITLE
Bad Download no real name and image extentions

### ISSUE THREAD

**Issue by johnfelipe** [hsd/sign#4]
Bad Download no real name and image extentions, dont show like:

![20130924_0950 medium](https://cloud.githubusercontent.com/assets/428820/2614219/3c9bc93e-bbe3-11e3-9a82-5dbd7c68e7c1.png)

For my instance show me:

![nomeaparece](https://cloud.githubusercontent.com/assets/428820/2614221/4cabc61c-bbe3-11e3-8a85-ab8994b741a7.png)

**Comment by johnfelipe** [comment]
Dont show me thumbnails only download way....

**Comment by mrvdb** [comment]
This typically means the listview-image module is not installed. Are you getting errors in the server log or in the browser console?

**Comment by johnfelipe** [comment]
But i have install listview-image:

![list](https://cloud.githubusercontent.com/assets/428820/2620661/142a1f28-bc42-11e3-861e-6e8cc98b73af.png)

**Comment by mrvdb** [comment]
ok, do you have errors in the server log or browser console?

**Comment by johnfelipe** [comment]
```
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 472, in _button_immediate_function
        function(cr, uid, ids, context=context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 391, in button_install
        self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 372, in state_update
        raise orm.except_orm(_('Error'), _("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
    except_osv: (u'Error', u"Intenta instalar el m\xf3dulo 'sign' que depende del m\xf3dulo 'listview_images'.\nEste \xfaltimo m\xf3dulo no est\xe1 disponible en su sistema.")
    2014-04-05 23:03:21,778 3875 INFO nuevabryan werkzeug: 192.168.1.184 - - [05/Apr/2014 23:03:21] "POST /web/dataset/call_button HTTP/1.1" 200 -
    2014-04-05 23:03:21,805 3875 INFO ? werkzeug: 192.168.1.184 - - [05/Apr/2014 23:03:21] "GET /web/static/src/img/warning.png HTTP/1.1" 200 -
    2014-04-05 23:03:36,114 3875 ERROR nuevabryan openerp.netsvc: Error
    Intenta instalar el mÃ³dulo 'sign' que depende del mÃ³dulo 'listview_images'.
    Este Ãºltimo mÃ³dulo no estÃ¡ disponible en su sistema.
    Traceback (most recent call last):
      File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
        result = ExportService.getService(service_name).dispatch(method, params)
      File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
        res = fn(db, uid, *params)
      File "/opt/openerp/server/openerp/osv/osv.py", line 190, in execute_kw
        return self.execute(db, uid, obj, method, *args, **kw or {})
      File "/opt/openerp/server/openerp/osv/osv.py", line 132, in wrapper
        return f(self, dbname, *args, **kwargs)
      File "/opt/openerp/server/openerp/osv/osv.py", line 199, in execute
        res = self.execute_cr(cr, uid, obj, method, *args, **kw)
      File "/opt/openerp/server/openerp/osv/osv.py", line 187, in execute_cr
        return getattr(object, method)(cr, uid, *args, **kw)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 424, in button_immediate_install
        return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 472, in _button_immediate_function
        function(cr, uid, ids, context=context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 391, in button_install
        self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context)
      File "/opt/openerp/server/openerp/addons/base/module/module.py", line 372, in state_update
        raise orm.except_orm(_('Error'), _("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
    except_osv: (u'Error', u"Intenta instalar el m\xf3dulo 'sign' que depende del m\xf3dulo 'listview_images'.\nEste \xfaltimo m\xf3dulo no est\xe1 disponible en su sistema.")
    2014-04-05 23:03:36,115 3875 INFO nuevabryan werkzeug: 192.168.1.184 - - [05/Apr/2014 23:03:36] "POST /web/dataset/call_button HTTP/1.1" 200 -
```

**Comment by johnfelipe** [comment]
![sign](https://cloud.githubusercontent.com/assets/428820/2623983/e89a12ac-bd16-11e3-9a18-9c262bc5f1d9.png)

**Comment by mrvdb** [comment]
this typically means listview_images is not in your module path, the system can't find the module. Does the 'addons_path' in your config file contain the folder where the listview_images module is?

**Comment by johnfelipe** [comment]
Please let me know how fix it

**Comment by mrvdb** [comment]
I suggest using http://help.openerp.com or getting someone to help you on site, this problem is outside the scope of this issue-tracker.

**Comment by johnfelipe** [comment]
How add listview_images in addons_path?

**Comment by johnfelipe** [comment]
work, but https://github.com/hsd/sign/issues/5#issuecomment-39823578
